### ISSUE TITLE
[Question] Cookies still showing up

### ISSUE THREAD

**Issue by ogalbnafets** [renickbuettner/matomo-plugin#3]
Hello!

I have a question.. I disabled the Cookie setting and use the middleware, so I don't have the javascript tags. I also enabled in Matomo the option to disable the cookies requesting.

But I am still getting cookies showed up:
![image](https://user-images.githubusercontent.com/70335936/158981041-b64d80e0-8eab-4da0-8309-2968a27418d6.png)

Do you know why this is happening or how can I avoid this? 
So the cookies are no problem but I would want a opt-out option, maybe you have a hint how I can realize this?

Thank you!!

**Comment by renickbuettner** [comment]
I took the working directly from the Matomo documentation. Actually it's setting a cookie - by default called "MATOMO_SESSID". By German GDPR it's called an essential cookie.

Did a short test on several domains (not subdomains). I couldn't reproduce that Matomo set a session id cookie. 

Are u on a recent version of Matomo? Your cookie key starts with "_pk" which was previous Piwik. Could imagine that cookie-less tracking isn't supported in old versions.

When the JavaScript snippet includes the opt-out ` _paq.push(['disableCookies']);` code - then technically the plugin is working as expected. 

If you really want to do tracking without cookies, you may use the server-side tracking function from this plugin.

**Comment by renickbuettner** [comment]
Feel free to re-open the ticket, if any questions left
