### ISSUE TITLE
Is Php 8 really useful ?

### ISSUE THREAD

**Issue by EricNiedergang** [renickbuettner/matomo-plugin#4]
Hello,

I see that php 8 is required to install your plugin.

Unfortunately, October CMS 2 is not compatible with php 8. Is it really required or the plugin could run under php 7.4+ ?

Best regards

**Comment by renickbuettner** [comment]
Hey, you're right – in theory it should also work with 7.4+. Personally I added this req because I want to force all my clients/ projects be on PHP 8 :-) 

But I will try and adjust the version back to 7.4+, give me some days

**Comment by renickbuettner** [comment]
@EricNiedergang The php version is not set to 7.3 and above. Installing on October v2 should work again.
